AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Resources:
    ApiGateway:
        Type: AWS::Serverless::Api
        Properties:
            Name: Okty Frontend Gateway
            StageName: Prod

    BuilderFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: src
            Handler: index.handle
            Runtime: nodejs12.x
            MemorySize: 128
            Timeout: 10
            AutoPublishAlias: prod
            DeploymentPreference:
                Type: AllAtOnce
                Hooks:
                    PreTraffic: !Ref BuilderFunctionPreTraffic
            Events:
                Api:
                    Type: Api
                    Properties:
                        RestApiId: !Ref ApiGateway
                        Path: /build
                        Method: POST

    BuilderFunctionPreTraffic:
        Type: AWS::Serverless::Function
        Properties:
            Handler: index.handler
            CodeUri: hooks/pre_traffic
            Policies:
                -   Version: "2012-10-17"
                    Statement:
                        -   Effect: "Allow"
                            Action:
                                - "codedeploy:PutLifecycleEventHookExecutionStatus"
                            Resource: !Sub 'arn:aws:codedeploy:${AWS::Region}:${AWS::AccountId}:deploymentgroup:${ServerlessDeploymentApplication}/*'
                -   Version: "2012-10-17"
                    Statement:
                        -   Effect: "Allow"
                            Action:
                                - "lambda:InvokeFunction"
                            Resource: !Ref BuilderFunction.Version
            Runtime: nodejs12.x
            FunctionName: 'CodeDeployHook_BuilderFunctionPreTraffic'
            DeploymentPreference:
                Enabled: false
            Timeout: 30
            Environment:
                Variables:
                    NewVersion: !Ref BuilderFunction.Version

Outputs:
    WebEndpoint:
        Description: "API Gateway endpoint URL for Prod stage"
        Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
